import { NextResponse } from "next/server";

export async function GET() {
  const jobs = [
    {
      id: "100",
      jobTitle: "Frontend Developer",
      companyName: "TechNova",
      location: "Chennai",
      industryType: "Information Technology",
      department: "Engineering",
      employmentType: "Full-time",
      roleCategory: "Software Development",
      shortDescription:
        "Build and maintain dynamic web applications using modern JavaScript frameworks. Collaborate with designers and backend teams to deliver seamless user experiences. Work in a fast-paced, innovative environment. Enjoy remote work flexibility and growth opportunities.",
      jobDescription:
        "TechNova is seeking a skilled Frontend Developer to join our innovative team in Chennai. You will be responsible for developing and maintaining high-quality web applications using React, TypeScript, and other modern JavaScript frameworks. Your role involves collaborating closely with UI/UX designers to implement pixel-perfect, responsive designs that enhance user experience. You will also work with backend developers to integrate APIs and ensure smooth functionality across the application. The ideal candidate is proficient in state management tools like Redux and has a strong understanding of web performance optimization techniques. You will participate in code reviews, contribute to architectural decisions, and adhere to best practices for clean, maintainable code. This role offers the opportunity to work on cutting-edge projects in a supportive, growth-oriented environment. Remote work options and flexible hours are available to ensure work-life balance. Candidates with experience in Tailwind CSS or similar frameworks are highly preferred. Join TechNova to shape the future of web development!",
      jobHighlights: [
        "Remote Work",
        "Flexible Hours",
        "Health Insurance",
        "Learning Stipend",
      ],
      keySkills: [
        "React",
        "JavaScript",
        "TypeScript",
        "Tailwind CSS",
        "Redux",
        "HTML5",
        "CSS3",
        "Git",
        "Webpack",
      ],
      educationRequirements: "B.E./B.Tech in Computer Science or related field",
      experienceLevel: "2-4 years",
      salaryRange: "₹8 LPA - ₹12 LPA",
      companyLogo: "https://via.placeholder.com/150?text=TechNova+Logo",
    },
    {
      id: "101",
      jobTitle: "UI/UX Designer",
      companyName: "Designify",
      location: "Remote",
      industryType: "Design Services",
      department: "Product Design",
      employmentType: "Contract",
      roleCategory: "UI/Design",
      shortDescription:
        "Design intuitive user interfaces for web and mobile platforms. Conduct user research and create prototypes to enhance user experience. Work remotely with international clients. Join a creative and dynamic design team.",
      jobDescription:
        "Designify is looking for a talented UI/UX Designer to create engaging and user-friendly interfaces for our global clients. Your primary responsibility will be to design intuitive user experiences for web and mobile applications, ensuring accessibility and aesthetic appeal. You will conduct user research, create wireframes, and develop interactive prototypes using tools like Figma and Adobe XD. Collaborating with product managers and developers, you will iterate on designs based on feedback and usability testing results. The role requires a deep understanding of user-centered design principles and the ability to translate complex requirements into simple, elegant solutions. You will also contribute to the development of design systems to ensure consistency across products. This is a remote contract position, offering the flexibility to work from anywhere while collaborating with a diverse, international team. Strong communication skills and a portfolio showcasing your design process are essential. Experience with animation tools like Principle is a plus. Join Designify to make a global impact through design!",
      jobHighlights: [
        "Remote Only",
        "International Clients",
        "Flexible Schedule",
      ],
      keySkills: [
        "Figma",
        "Adobe XD",
        "User Research",
        "Wireframing",
        "Prototyping",
        "Usability Testing",
        "Design Systems",
        "Principle",
        "Sketch",
      ],
      educationRequirements: "Bachelor’s in Design or equivalent experience",
      experienceLevel: "3-5 years",
      salaryRange: "₹10 LPA - ₹15 LPA",
      companyLogo: "https://via.placeholder.com/150?text=Designify+Logo",
    },
    {
      id: "102",
      jobTitle: "Backend Engineer",
      companyName: "DataStack",
      location: "Bangalore",
      industryType: "FinTech",
      department: "Backend",
      employmentType: "Full-time",
      roleCategory: "Backend Development",
      shortDescription:
        "Develop scalable APIs and manage cloud-based databases. Work on cutting-edge FinTech solutions. Collaborate with cross-functional teams in Bangalore. Enjoy equity options and a product-driven culture.",
      jobDescription:
        "DataStack, a leading FinTech company in Bangalore, is hiring a Backend Engineer to design and implement scalable backend systems. You will develop robust APIs using Node.js and Express, ensuring high performance and security for financial applications. Your role includes managing MongoDB databases, optimizing queries, and integrating with AWS cloud services for seamless deployment. You will collaborate with frontend developers, data scientists, and product managers to deliver end-to-end solutions that meet customer needs. The ideal candidate has experience with microservices architecture and containerization tools like Docker. You will also participate in code reviews, write unit tests, and ensure adherence to CI/CD pipelines for continuous delivery. This role offers the opportunity to work on innovative financial products that impact millions of users. DataStack provides equity options, fostering a sense of ownership in the company’s success. Strong problem-solving skills and a passion for building reliable systems are essential. Join DataStack to drive the future of finance!",
      jobHighlights: [
        "Product-based Company",
        "Equity Options",
        "AWS Certification Support",
      ],
      keySkills: [
        "Node.js",
        "Express",
        "MongoDB",
        "AWS",
        "Docker",
        "Microservices",
        "REST APIs",
        "Jest",
        "CI/CD",
      ],
      educationRequirements: "B.E./B.Tech or M.C.A",
      experienceLevel: "4-6 years",
      salaryRange: "₹15 LPA - ₹22 LPA",
      companyLogo: "https://via.placeholder.com/150?text=DataStack+Logo",
    },
    {
      id: "103",
      jobTitle: "Full Stack Developer",
      companyName: "Nexlify",
      location: "Hyderabad",
      industryType: "E-Commerce",
      department: "Engineering",
      employmentType: "Full-time",
      roleCategory: "Software Development",
      shortDescription:
        "Build end-to-end e-commerce solutions using MERN stack. Collaborate with product teams to enhance user experience. Work in Hyderabad’s vibrant tech hub. Enjoy career growth and team outings.",
      jobDescription:
        "Nexlify is seeking a Full Stack Developer to join our Hyderabad team, focusing on building scalable e-commerce platforms. You will work on the entire development lifecycle, from designing frontends with React to developing backend APIs with Node.js and Express. Your role involves integrating MongoDB databases, optimizing application performance, and ensuring seamless user experiences. You will collaborate with product managers and designers to implement features like product search, payment gateways, and user authentication. The ideal candidate is proficient in both frontend and backend technologies, with a strong understanding of RESTful APIs and GraphQL. You will also contribute to code reviews, write automated tests, and participate in agile sprints. Nexlify fosters a collaborative culture with regular team outings and learning opportunities. Experience with Redux Toolkit and TypeScript is a plus. This role offers significant growth potential in the fast-growing e-commerce sector. Join Nexlify to create impactful shopping experiences!",
      jobHighlights: [
        "Team Outings",
        "Learning Opportunities",
        "Health Benefits",
      ],
      keySkills: [
        "React",
        "Node.js",
        "Express",
        "MongoDB",
        "GraphQL",
        "TypeScript",
        "Redux Toolkit",
        "Jest",
        "Agile",
      ],
      educationRequirements: "B.E./B.Tech in Computer Science or related field",
      experienceLevel: "3-5 years",
      salaryRange: "₹12 LPA - ₹18 LPA",
      companyLogo: "https://via.placeholder.com/150?text=Nexlify+Logo",
    },
    {
      id: "104",
      jobTitle: "Data Scientist",
      companyName: "IntelliCore",
      location: "Pune",
      industryType: "Analytics",
      department: "Data Science",
      employmentType: "Full-time",
      roleCategory: "Data Science",
      shortDescription:
        "Develop machine learning models to solve business problems. Analyze large datasets and provide actionable insights. Work in Pune’s growing tech ecosystem. Join a data-driven team.",
      jobDescription:
        "IntelliCore is hiring a Data Scientist to join our Pune team, focusing on leveraging data to drive business decisions. You will develop and deploy machine learning models using Python, TensorFlow, and Scikit-learn to solve complex problems in various domains. Your role involves analyzing large datasets, identifying trends, and presenting actionable insights to stakeholders. You will collaborate with data engineers to build data pipelines and ensure data quality. The ideal candidate has strong expertise in statistical modeling, natural language processing, and time-series analysis. You will also experiment with deep learning frameworks and contribute to A/B testing initiatives. IntelliCore emphasizes a data-driven culture, offering access to cutting-edge tools and cloud platforms like AWS. Experience with SQL and data visualization tools like Tableau is highly valued. This role provides opportunities to work on impactful projects and grow as a data science leader. Join IntelliCore to transform data into innovation!",
      jobHighlights: ["Cutting-edge Tools", "Cloud Platforms", "Career Growth"],
      keySkills: [
        "Python",
        "TensorFlow",
        "Scikit-learn",
        "SQL",
        "Tableau",
        "NLP",
        "Deep Learning",
        "AWS",
        "Statistical Modeling",
      ],
      educationRequirements:
        "M.Sc./Ph.D. in Data Science, Statistics, or related field",
      experienceLevel: "3-6 years",
      salaryRange: "₹14 LPA - ₹20 LPA",
      companyLogo: "https://via.placeholder.com/150?text=IntelliCore+Logo",
    },
    {
      id: "105",
      jobTitle: "DevOps Engineer",
      companyName: "CloudPeak",
      location: "Gurgaon",
      industryType: "Cloud Computing",
      department: "Operations",
      employmentType: "Full-time",
      roleCategory: "DevOps",
      shortDescription:
        "Manage cloud infrastructure and CI/CD pipelines. Automate deployment processes for scalable applications. Work in Gurgaon’s tech hub. Enjoy a collaborative DevOps culture.",
      jobDescription:
        "CloudPeak is seeking a DevOps Engineer to join our Gurgaon team, focusing on building and maintaining robust cloud infrastructure. You will design and manage CI/CD pipelines using tools like Jenkins, GitLab CI, and Kubernetes to ensure smooth deployments. Your role involves automating infrastructure provisioning with Terraform and monitoring systems using Prometheus and Grafana. You will collaborate with development teams to optimize application performance and ensure high availability. The ideal candidate has strong experience with AWS, Docker, and Linux system administration. You will also implement security best practices and manage disaster recovery processes. CloudPeak fosters a collaborative DevOps culture, encouraging continuous learning and certification support. Experience with Ansible or similar configuration management tools is a plus. This role offers the opportunity to work on large-scale cloud projects and grow as a DevOps expert. Join CloudPeak to drive operational excellence!",
      jobHighlights: [
        "Certification Support",
        "Collaborative Culture",
        "Health Benefits",
      ],
      keySkills: [
        "AWS",
        "Kubernetes",
        "Jenkins",
        "Terraform",
        "Docker",
        "Prometheus",
        "Grafana",
        "Linux",
        "Ansible",
      ],
      educationRequirements: "B.E./B.Tech in Computer Science or related field",
      experienceLevel: "3-5 years",
      salaryRange: "₹12 LPA - ₹18 LPA",
      companyLogo: "https://via.placeholder.com/150?text=CloudPeak+Logo",
    },
    {
      id: "106",
      jobTitle: "Mobile App Developer",
      companyName: "AppVibe",
      location: "Mumbai",
      industryType: "Mobile Technology",
      department: "Engineering",
      employmentType: "Full-time",
      roleCategory: "Mobile Development",
      shortDescription:
        "Develop cross-platform mobile apps using Flutter. Collaborate with designers to create engaging user interfaces. Work in Mumbai’s dynamic tech scene. Join a creative mobile dev team.",
      jobDescription:
        "AppVibe is hiring a Mobile App Developer to join our Mumbai team, focusing on building high-quality mobile applications. You will develop cross-platform apps using Flutter, ensuring performance and compatibility across iOS and Android devices. Your role involves collaborating with UI/UX designers to implement intuitive interfaces and integrating RESTful APIs for backend connectivity. You will also write unit tests, optimize app performance, and ensure adherence to app store guidelines. The ideal candidate has experience with Dart, state management libraries like Provider, and Firebase integration. You will participate in agile development cycles and contribute to app feature planning. AppVibe offers a creative environment with opportunities to work on diverse projects, from social apps to enterprise solutions. Knowledge of native development (Swift/Kotlin) is a plus. This role provides significant growth potential in the mobile technology space. Join AppVibe to create apps that inspire!",
      jobHighlights: [
        "Creative Environment",
        "Diverse Projects",
        "Team Events",
      ],
      keySkills: [
        "Flutter",
        "Dart",
        "Firebase",
        "REST APIs",
        "Provider",
        "iOS",
        "Android",
        "Unit Testing",
        "Agile",
      ],
      educationRequirements: "B.E./B.Tech in Computer Science or related field",
      experienceLevel: "2-4 years",
      salaryRange: "₹10 LPA - ₹15 LPA",
      companyLogo: "https://via.placeholder.com/150?text=AppVibe+Logo",
    },
    {
      id: "107",
      jobTitle: "Product Manager",
      companyName: "GrowEasy",
      location: "Delhi",
      industryType: "SaaS",
      department: "Product Management",
      employmentType: "Full-time",
      roleCategory: "Product Management",
      shortDescription:
        "Lead product development for SaaS solutions. Define product roadmaps and collaborate with cross-functional teams. Work in Delhi’s vibrant startup ecosystem. Drive customer-centric innovation.",
      jobDescription:
        "GrowEasy is seeking a Product Manager to lead the development of our SaaS platform in Delhi. You will define product vision, create roadmaps, and prioritize features based on customer needs and market trends. Your role involves collaborating with engineering, design, and marketing teams to deliver high-quality products. You will conduct market research, gather user feedback, and analyze product metrics to drive continuous improvement. The ideal candidate has strong experience with agile methodologies, user story creation, and tools like Jira or Trello. You will also work closely with stakeholders to align product goals with business objectives. GrowEasy fosters a customer-centric culture, offering opportunities to innovate in the SaaS space. Experience with B2B products or subscription-based models is a plus. This role provides significant leadership growth and the chance to impact thousands of users. Join GrowEasy to shape the future of SaaS!",
      jobHighlights: [
        "Leadership Growth",
        "Customer-centric Culture",
        "Stock Options",
      ],
      keySkills: [
        "Agile",
        "Jira",
        "User Stories",
        "Market Research",
        "Product Roadmapping",
        "Stakeholder Management",
        "Metrics Analysis",
        "Trello",
      ],
      educationRequirements: "MBA or B.E./B.Tech in Computer Science",
      experienceLevel: "4-7 years",
      salaryRange: "₹18 LPA - ₹25 LPA",
      companyLogo: "https://via.placeholder.com/150?text=GrowEasy+Logo",
    },
    {
      id: "108",
      jobTitle: "Cybersecurity Analyst",
      companyName: "SecureNet",
      location: "Noida",
      industryType: "Cybersecurity",
      department: "Security",
      employmentType: "Full-time",
      roleCategory: "Cybersecurity",
      shortDescription:
        "Monitor and protect systems from cyber threats. Conduct vulnerability assessments and implement security measures. Work in Noida’s tech hub. Join a proactive security team.",
      jobDescription:
        "SecureNet is hiring a Cybersecurity Analyst to join our Noida team, focusing on safeguarding our systems and data. You will monitor network traffic, detect potential threats, and respond to security incidents using tools like Splunk and Wireshark. Your role involves conducting vulnerability assessments, implementing firewalls, and ensuring compliance with industry standards like ISO 27001. You will collaborate with IT teams to strengthen system security and educate employees on best practices. The ideal candidate has experience with penetration testing, SIEM tools, and cloud security frameworks. You will also contribute to security audits and develop incident response plans. SecureNet offers a proactive environment with access to cutting-edge security tools and certifications. Knowledge of GDPR or PCI-DSS compliance is a plus. This role provides opportunities to grow as a cybersecurity expert. Join SecureNet to protect the digital world!",
      jobHighlights: [
        "Cutting-edge Tools",
        "Certification Support",
        "Health Benefits",
      ],
      keySkills: [
        "Splunk",
        "Wireshark",
        "Penetration Testing",
        "SIEM",
        "Firewalls",
        "Cloud Security",
        "ISO 27001",
        "Incident Response",
      ],
      educationRequirements: "B.E./B.Tech in Cybersecurity or related field",
      experienceLevel: "3-5 years",
      salaryRange: "₹12 LPA - ₹18 LPA",
      companyLogo: "https://via.placeholder.com/150?text=SecureNet+Logo",
    },
    {
      id: "109",
      jobTitle: "AI Engineer",
      companyName: "SmartAI",
      location: "Remote",
      industryType: "Artificial Intelligence",
      department: "AI Research",
      employmentType: "Full-time",
      roleCategory: "AI Development",
      shortDescription:
        "Build and deploy AI models for innovative applications. Work with cutting-edge AI frameworks remotely. Collaborate with global AI experts. Drive advancements in AI technology.",
      jobDescription:
        "SmartAI is seeking an AI Engineer to join our remote team, focusing on developing advanced AI solutions. You will design, train, and deploy machine learning models using frameworks like PyTorch and TensorFlow for applications in NLP, computer vision, and more. Your role involves preprocessing large datasets, optimizing model performance, and integrating models into production environments. You will collaborate with data scientists and software engineers to build scalable AI systems. The ideal candidate has strong experience with deep遵义360竞彩软件_360竞彩足球官网_360竞彩足球比分直播-【有保障】 deep learning, reinforcement learning, and cloud platforms like GCP or Azure. You will also experiment with generative AI models and contribute to research initiatives. SmartAI offers a flexible, remote work environment with access to global AI communities and conferences. Knowledge of MLOps tools like Kubeflow is a plus. This role provides opportunities to push the boundaries of AI innovation. Join SmartAI to shape the future of intelligence!",
      jobHighlights: [
        "Remote Work",
        "Global Collaboration",
        "Conference Access",
      ],
      keySkills: [
        "PyTorch",
        "TensorFlow",
        "Deep Learning",
        "NLP",
        "Computer Vision",
        "GCP",
        "MLOps",
        "Reinforcement Learning",
        "Kubeflow",
      ],
      educationRequirements: "M.Sc./Ph.D. in Computer Science or related field",
      experienceLevel: "3-6 years",
      salaryRange: "₹15 LPA - ₹22 LPA",
      companyLogo: "https://via.placeholder.com/150?text=SmartAI+Logo",
    },
    {
      id: "110",
      jobTitle: "Cloud Architect",
      companyName: "SkyNet Solutions",
      location: "Bangalore",
      industryType: "Cloud Computing",
      department: "Architecture",
      employmentType: "Full-time",
      roleCategory: "Cloud Architecture",
      shortDescription:
        "Design and implement cloud solutions for enterprise clients. Optimize cloud infrastructure for scalability. Work in Bangalore’s tech hub. Lead innovative cloud projects.",
      jobDescription:
        "SkyNet Solutions is hiring a Cloud Architect to design and implement cloud infrastructure for our enterprise clients in Bangalore. You will architect scalable, secure, and cost-efficient solutions using AWS, Azure, or GCP. Your role involves assessing client requirements, designing cloud migration strategies, and overseeing implementation. You will collaborate with DevOps and security teams to ensure high availability and compliance with industry standards. The ideal candidate has expertise in serverless computing, containerization, and hybrid cloud environments. You will also provide technical leadership, mentor junior engineers, and stay updated on cloud trends. SkyNet Solutions offers a dynamic environment with opportunities to work on cutting-edge projects. Certifications like AWS Solutions Architect or Azure Architect are highly valued. This role provides significant growth in cloud technology leadership. Join SkyNet Solutions to build the future of cloud computing!",
      jobHighlights: [
        "Leadership Opportunities",
        "Cutting-edge Projects",
        "Certification Support",
      ],
      keySkills: [
        "AWS",
        "Azure",
        "GCP",
        "Serverless",
        "Kubernetes",
        "Hybrid Cloud",
        "Cloud Migration",
        "Cost Optimization",
      ],
      educationRequirements: "B.E./B.Tech in Computer Science or related field",
      experienceLevel: "5-8 years",
      salaryRange: "₹20 LPA - ₹30 LPA",
      companyLogo: "https://via.placeholder.com/150?text=SkyNet+Logo",
    },
    {
      id: "111",
      jobTitle: "Business Analyst",
      companyName: "GrowSmart",
      location: "Mumbai",
      industryType: "Consulting",
      department: "Business Analysis",
      employmentType: "Full-time",
      roleCategory: "Business Analysis",
      shortDescription:
        "Bridge business needs with technical solutions. Gather requirements and create process flows. Work in Mumbai’s corporate hub. Drive impactful business transformations.",
      jobDescription:
        "GrowSmart is seeking a Business Analyst to join our Mumbai team, focusing on delivering value through effective requirement analysis. You will work with stakeholders to gather and document business requirements, create process flows, and define user stories for technical teams. Your role involves analyzing business processes, identifying improvement opportunities, and facilitating workshops to align solutions with client goals. You will collaborate with developers and testers to ensure successful project delivery. The ideal candidate has strong experience with tools like Jira, Confluence, and Visio, along with knowledge of agile and waterfall methodologies. You will also contribute to data analysis and reporting to support decision-making. GrowSmart offers a collaborative environment with opportunities to work on diverse consulting projects. CBAP or PMP certification is a plus. This role provides growth in business analysis and stakeholder management. Join GrowSmart to drive business success!",
      jobHighlights: [
        "Diverse Projects",
        "Collaborative Culture",
        "Health Benefits",
      ],
      keySkills: [
        "Jira",
        "Confluence",
        "Visio",
        "Agile",
        "Waterfall",
        "Stakeholder Management",
        "Process Mapping",
        "Data Analysis",
      ],
      educationRequirements: "MBA or B.E./B.Tech",
      experienceLevel: "3-5 years",
      salaryRange: "₹10 LPA - ₹15 LPA",
      companyLogo: "https://via.placeholder.com/150?text=GrowSmart+Logo",
    },
    {
      id: "112",
      jobTitle: "Game Developer",
      companyName: "PlayVerse",
      location: "Pune",
      industryType: "Gaming",
      department: "Game Development",
      employmentType: "Full-time",
      roleCategory: "Game Development",
      shortDescription:
        "Create immersive games using Unity. Collaborate with artists and designers for engaging gameplay. Work in Pune’s gaming hub. Join a passionate game dev team.",
      jobDescription:
        "PlayVerse is hiring a Game Developer to join our Pune team, focusing on building exciting games. You will develop games using Unity and C#, creating engaging gameplay mechanics and immersive worlds. Your role involves collaborating with artists to implement 3D models and with designers to refine game mechanics. You will optimize game performance for multiple platforms, including mobile and PC. The ideal candidate has experience with shader programming, physics engines, and multiplayer networking. You will also contribute to game testing and debugging to ensure a polished product. PlayVerse fosters a creative environment with opportunities to work on original game titles. Knowledge of Unreal Engine or AR/VR development is a plus. This role offers growth in the dynamic gaming industry. Join PlayVerse to bring fun to millions of players!",
      jobHighlights: ["Creative Environment", "Original Titles", "Team Events"],
      keySkills: [
        "Unity",
        "C#",
        "Shader Programming",
        "Physics Engines",
        "Multiplayer Networking",
        "3D Modeling",
        "Game Optimization",
        "Debugging",
      ],
      educationRequirements: "B.E./B.Tech in Computer Science or related field",
      experienceLevel: "2-4 years",
      salaryRange: "₹8 LPA - ₹12 LPA",
      companyLogo: "https://via.placeholder.com/150?text=PlayVerse+Logo",
    },
    {
      id: "113",
      jobTitle: "QA Engineer",
      companyName: "TestRight",
      location: "Chennai",
      industryType: "Quality Assurance",
      department: "QA",
      employmentType: "Full-time",
      roleCategory: "Quality Assurance",
      shortDescription:
        "Ensure software quality through automated and manual testing. Collaborate with developers to identify bugs. Work in Chennai’s tech ecosystem. Join a detail-oriented QA team.",
      jobDescription:
        "TestRight is seeking a QA Engineer to join our Chennai team, focusing on ensuring the quality of our software products. You will design and execute test cases, perform manual and automated testing, and report defects using tools like Selenium and JIRA. Your role involves collaborating with developers to reproduce issues and verify fixes, ensuring high-quality releases. You will also contribute to test automation frameworks and performance testing using tools like JMeter. The ideal candidate has experience with API testing, regression testing, and agile methodologies. You will participate in sprint planning and provide input on testability of features. TestRight offers a supportive environment with opportunities to learn advanced QA tools. Knowledge of CI/CD integration is a plus. This role provides growth in quality assurance expertise. Join TestRight to deliver flawless software!",
      jobHighlights: [
        "Learning Opportunities",
        "Supportive Culture",
        "Health Benefits",
      ],
      keySkills: [
        "Selenium",
        "JIRA",
        "JMeter",
        "API Testing",
        "Regression Testing",
        "Test Automation",
        "Agile",
        "CI/CD",
      ],
      educationRequirements: "B.E./B.Tech in Computer Science or related field",
      experienceLevel: "2-4 years",
      salaryRange: "₹7 LPA - ₹11 LPA",
      companyLogo: "https://via.placeholder.com/150?text=TestRight+Logo",
    },
    {
      id: "114",
      jobTitle: "Blockchain Developer",
      companyName: "ChainWorks",
      location: "Remote",
      industryType: "Blockchain",
      department: "Engineering",
      employmentType: "Full-time",
      roleCategory: "Blockchain Development",
      shortDescription:
        "Build decentralized applications using Ethereum. Develop smart contracts and ensure security. Work remotely with a global team. Drive blockchain innovation.",
      jobDescription:
        "ChainWorks is hiring a Blockchain Developer to join our remote team, focusing on building decentralized applications. You will develop and deploy smart contracts on Ethereum using Solidity, ensuring security and scalability. Your role involves integrating blockchain solutions with frontend applications and optimizing gas costs. You will collaborate with product teams to design tokenomics and implement Web3 protocols. The ideal candidate has experience with Truffle, Hardhat, and IPFS for decentralized storage. You will also conduct security audits and participate in code reviews to maintain high standards. ChainWorks offers a flexible, remote environment with opportunities to work on cutting-edge blockchain projects. Knowledge of layer-2 solutions like Polygon is a plus. This role provides growth in the rapidly evolving blockchain space. Join ChainWorks to shape the decentralized future!",
      jobHighlights: ["Remote Work", "Cutting-edge Projects", "Global Team"],
      keySkills: [
        "Solidity",
        "Ethereum",
        "Truffle",
        "Hardhat",
        "IPFS",
        "Web3",
        "Smart Contracts",
        "Security Audits",
      ],
      educationRequirements: "B.E./B.Tech in Computer Science or related field",
      experienceLevel: "3-5 years",
      salaryRange: "₹15 LPA - ₹22 LPA",
      companyLogo: "https://via.placeholder.com/150?text=ChainWorks+Logo",
    },
    {
      id: "115",
      jobTitle: "Technical Writer",
      companyName: "DocuTech",
      location: "Hyderabad",
      industryType: "Technical Writing",
      department: "Documentation",
      employmentType: "Full-time",
      roleCategory: "Technical Writing",
      shortDescription:
        "Create clear technical documentation for software products. Collaborate with developers and product teams. Work in Hyderabad’s tech hub. Join a detail-oriented writing team.",
      jobDescription:
        "DocuTech is seeking a Technical Writer to join our Hyderabad team, focusing on producing high-quality documentation for software products. You will create user manuals, API documentation, and knowledge base articles, ensuring clarity and accuracy. Your role involves collaborating with developers, product managers, and QA teams to gather information and validate content. You will use tools like MadCap Flare and Markdown to structure and publish documentation. The ideal candidate has strong writing skills, experience with DITA, and familiarity with software development processes. You will also maintain documentation repositories and ensure consistency across deliverables. DocuTech offers a supportive environment with opportunities to learn advanced documentation tools. Knowledge of video tutorial creation is a plus. This role provides growth in technical communication. Join DocuTech to make complex technology accessible!",
      jobHighlights: [
        "Supportive Culture",
        "Learning Opportunities",
        "Health Benefits",
      ],
      keySkills: [
        "MadCap Flare",
        "Markdown",
        "DITA",
        "API Documentation",
        "Technical Writing",
        "Collaboration",
        "Video Tutorials",
        "Content Management",
      ],
      educationRequirements:
        "Bachelor’s in English, Technical Communication, or related field",
      experienceLevel: "2-4 years",
      salaryRange: "₹8 LPA - ₹12 LPA",
      companyLogo: "https://via.placeholder.com/150?text=DocuTech+Logo",
    },
    {
      id: "116",
      jobTitle: "Embedded Systems Engineer",
      companyName: "TechForge",
      location: "Bangalore",
      industryType: "IoT",
      department: "Engineering",
      employmentType: "Full-time",
      roleCategory: "Embedded Systems",
      shortDescription:
        "Develop firmware for IoT devices. Optimize embedded systems for performance. Work in Bangalore’s IoT hub. Join an innovative hardware team.",
      jobDescription:
        "TechForge is hiring an Embedded Systems Engineer to join our Bangalore team, focusing on developing firmware for IoT devices. You will design and implement embedded software using C/C++ for microcontrollers like ARM Cortex. Your role involves optimizing system performance, ensuring low power consumption, and integrating sensors and communication protocols like MQTT. You will collaborate with hardware engineers to validate designs and debug issues using tools like JTAG. The ideal candidate has experience with RTOS, Linux kernel development, and wireless technologies like Bluetooth or Zigbee. You will also contribute to unit testing and documentation for regulatory compliance. TechForge offers an innovative environment with access to cutting-edge IoT projects. Knowledge of FPGA programming is a plus. This role provides growth in embedded systems expertise. Join TechForge to power the IoT revolution!",
      jobHighlights: [
        "Cutting-edge Projects",
        "Innovative Culture",
        "Health Benefits",
      ],
      keySkills: [
        "C/C++",
        "ARM Cortex",
        "RTOS",
        "MQTT",
        "Bluetooth",
        "Zigbee",
        "JTAG",
        "Linux Kernel",
      ],
      educationRequirements: "B.E./B.Tech in Electronics or Computer Science",
      experienceLevel: "3-5 years",
      salaryRange: "₹12 LPA - ₹18 LPA",
      companyLogo: "https://via.placeholder.com/150?text=TechForge+Logo",
    },
    {
      id: "117",
      jobTitle: "Network Engineer",
      companyName: "ConnectSphere",
      location: "Gurgaon",
      industryType: "Networking",
      department: "IT Operations",
      employmentType: "Full-time",
      roleCategory: "Network Engineering",
      shortDescription:
        "Design and maintain enterprise networks. Ensure network security and performance. Work in Gurgaon’s tech hub. Join a proactive IT team.",
      jobDescription:
        "ConnectSphere is seeking a Network Engineer to join our Gurgaon team, focusing on designing and maintaining enterprise networks. You will configure and troubleshoot routers, switches, and firewalls using Cisco and Juniper equipment. Your role involves monitoring network performance, implementing security protocols, and ensuring uptime for critical systems. You will collaborate with IT teams to support cloud connectivity and VPN solutions. The ideal candidate has experience with SDN, VLANs, and network monitoring tools like SolarWinds. You will also conduct capacity planning and participate in disaster recovery drills. ConnectSphere offers a proactive environment with opportunities to earn certifications like CCNP. Knowledge of 5G or IoT networking is a plus. This role provides growth in network engineering expertise. Join ConnectSphere to keep businesses connected!",
      jobHighlights: [
        "Certification Support",
        "Proactive Culture",
        "Health Benefits",
      ],
      keySkills: [
        "Cisco",
        "Juniper",
        "SDN",
        "VLANs",
        "SolarWinds",
        "Firewalls",
        "VPN",
        "Network Monitoring",
      ],
      educationRequirements: "B.E./B.Tech in Computer Science or related field",
      experienceLevel: "3-5 years",
      salaryRange: "₹10 LPA - ₹15 LPA",
      companyLogo: "https://via.placeholder.com/150?text=ConnectSphere+Logo",
    },
    {
      id: "118",
      jobTitle: "AR/VR Developer",
      companyName: "VirtuaLab",
      location: "Pune",
      industryType: "Augmented Reality",
      department: "Engineering",
      employmentType: "Full-time",
      roleCategory: "AR/VR Development",
      shortDescription:
        "Create immersive AR/VR experiences using Unity. Collaborate with designers for innovative applications. Work in Pune’s tech scene. Join a futuristic dev team.",
      jobDescription:
        "VirtuaLab is hiring an AR/VR Developer to join our Pune team, focusing on building immersive augmented and virtual reality applications. You will develop experiences using Unity and C#, integrating 3D models and spatial audio for platforms like Oculus and HoloLens. Your role involves optimizing performance for real-time rendering and implementing interaction systems using hand-tracking or controllers. You will collaborate with designers and product managers to create applications for gaming, education, or enterprise use cases. The ideal candidate has experience with ARKit, ARCore, or WebXR for cross-platform development. You will also contribute to testing and debugging to ensure seamless user experiences. VirtuaLab offers a futuristic environment with access to cutting-edge AR/VR hardware. Knowledge of 3D modeling tools like Blender is a plus. This role provides growth in immersive technology. Join VirtuaLab to redefine reality!",
      jobHighlights: [
        "Cutting-edge Hardware",
        "Futuristic Projects",
        "Team Events",
      ],
      keySkills: [
        "Unity",
        "C#",
        "ARKit",
        "ARCore",
        "WebXR",
        "3D Modeling",
        "Spatial Audio",
        "Real-time Rendering",
      ],
      educationRequirements: "B.E./B.Tech in Computer Science or related field",
      experienceLevel: "2-4 years",
      salaryRange: "₹10 LPA - ₹15 LPA",
      companyLogo: "https://via.placeholder.com/150?text=VirtuaLab+Logo",
    },
    {
      id: "119",
      jobTitle: "Digital Marketing Specialist",
      companyName: "BrandBuzz",
      location: "Delhi",
      industryType: "Marketing",
      department: "Marketing",
      employmentType: "Full-time",
      roleCategory: "Digital Marketing",
      shortDescription:
        "Drive online campaigns to boost brand visibility. Optimize SEO and manage social media. Work in Delhi’s vibrant marketing hub. Join a creative marketing team.",
      jobDescription:
        "BrandBuzz is seeking a Digital Marketing Specialist to join our Delhi team, focusing on enhancing brand presence online. You will plan and execute digital campaigns across platforms like Google Ads, Facebook, and LinkedIn, optimizing for ROI. Your role involves managing SEO strategies, analyzing website traffic, and creating engaging social media content. You will collaborate with content creators and designers to develop compelling visuals and copy. The ideal candidate has experience with tools like Google Analytics, SEMrush, and Hootsuite, along with knowledge of email marketing platforms. You will also monitor campaign performance and provide data-driven recommendations. BrandBuzz offers a creative environment with opportunities to work on diverse client projects. Certifications like Google Ads or HubSpot are a plus. This role provides growth in digital marketing expertise. Join BrandBuzz to amplify brands online!",
      jobHighlights: [
        "Creative Environment",
        "Diverse Clients",
        "Health Benefits",
      ],
      keySkills: [
        "Google Analytics",
        "SEMrush",
        "Hootsuite",
        "SEO",
        "Google Ads",
        "Social Media",
        "Email Marketing",
        "Content Strategy",
      ],
      educationRequirements: "Bachelor’s in Marketing or related field",
      experienceLevel: "2-4 years",
      salaryRange: "₹8 LPA - ₹12 LPA",
      companyLogo: "https://via.placeholder.com/150?text=BrandBuzz+Logo",
    },
    {
      id: "120",
      jobTitle: "Database Administrator",
      companyName: "DataVault",
      location: "Chennai",
      industryType: "Data Management",
      department: "IT Operations",
      employmentType: "Full-time",
      roleCategory: "Database Administration",
      shortDescription:
        "Manage and optimize enterprise databases. Ensure data security and performance. Work in Chennai’s tech hub. Join a reliable DBA team.",
      jobDescription:
        "DataVault is hiring a Database Administrator to join our Chennai team, focusing on managing enterprise databases. You will administer and optimize databases like MySQL, PostgreSQL, and Oracle, ensuring high availability and performance. Your role involves designing database schemas, writing complex SQL queries, and implementing backup strategies. You will collaborate with developers to support application needs and ensure data security through encryption and access controls. The ideal candidate has experience with cloud databases like AWS RDS and performance tuning tools. You will also conduct regular audits and participate in disaster recovery planning. DataVault offers a reliable environment with opportunities to learn advanced database technologies. Knowledge of NoSQL databases like MongoDB is a plus. This role provides growth in database management expertise. Join DataVault to safeguard critical data!",
      jobHighlights: [
        "Reliable Environment",
        "Learning Opportunities",
        "Health Benefits",
      ],
      keySkills: [
        "MySQL",
        "PostgreSQL",
        "Oracle",
        "AWS RDS",
        "SQL",
        "Backup Strategies",
        "Performance Tuning",
        "Data Security",
      ],
      educationRequirements: "B.E./B.Tech in Computer Science or related field",
      experienceLevel: "3-5 years",
      salaryRange: "₹10 LPA - ₹15 LPA",
      companyLogo: "https://via.placeholder.com/150?text=DataVault+Logo",
    },
    {
      id: "121",
      jobTitle: "Scrum Master",
      companyName: "AgilePeak",
      location: "Hyderabad",
      industryType: "Software Development",
      department: "Project Management",
      employmentType: "Full-time",
      roleCategory: "Scrum Master",
      shortDescription:
        "Facilitate agile processes and coach teams. Drive sprint success and remove blockers. Work in Hyderabad’s tech hub. Join a dynamic agile team.",
      jobDescription:
        "AgilePeak is seeking a Scrum Master to join our Hyderabad team, focusing on enabling high-performing agile teams. You will facilitate daily stand-ups, sprint planning, and retrospectives, ensuring adherence to Scrum principles. Your role involves coaching team members on agile best practices, removing impediments, and fostering a collaborative environment. You will collaborate with product owners to refine backlogs and ensure clear communication of priorities. The ideal candidate has experience with tools like Jira, Confluence, and SAFe frameworks, along with strong conflict resolution skills. You will also track team metrics and drive continuous improvement in processes. AgilePeak offers a dynamic environment with opportunities to work on diverse projects. CSM or PSM certification is highly valued. This role provides growth in agile leadership. Join AgilePeak to empower teams to succeed!",
      jobHighlights: [
        "Dynamic Environment",
        "Leadership Growth",
        "Health Benefits",
      ],
      keySkills: [
        "Jira",
        "Confluence",
        "Scrum",
        "SAFe",
        "Coaching",
        "Conflict Resolution",
        "Sprint Planning",
        "Metrics Tracking",
      ],
      educationRequirements: "B.E./B.Tech or MBA",
      experienceLevel: "3-5 years",
      salaryRange: "₹12 LPA - ₹18 LPA",
      companyLogo: "https://via.placeholder.com/150?text=AgilePeak+Logo",
    },
    {
      id: "122",
      jobTitle: "System Administrator",
      companyName: "InfraCore",
      location: "Noida",
      industryType: "IT Services",
      department: "IT Operations",
      employmentType: "Full-time",
      roleCategory: "System Administration",
      shortDescription:
        "Manage IT infrastructure and ensure system reliability. Support servers and networks. Work in Noida’s tech hub. Join a proactive IT team.",
      jobDescription:
        "InfraCore is hiring a System Administrator to join our Noida team, focusing on maintaining robust IT infrastructure. You will manage Windows and Linux servers, configure virtualization platforms like VMware, and ensure system security. Your role involves monitoring performance, applying patches, and troubleshooting hardware or software issues. You will collaborate with network engineers to support connectivity and backup systems. The ideal candidate has experience with Active Directory, scripting in PowerShell or Bash, and cloud platforms like Azure. You will also document processes and participate in capacity planning. InfraCore offers a proactive environment with opportunities to learn advanced IT tools. Knowledge of ITIL frameworks is a plus. This role provides growth in system administration expertise. Join InfraCore to keep systems running smoothly!",
      jobHighlights: [
        "Proactive Environment",
        "Learning Opportunities",
        "Health Benefits",
      ],
      keySkills: [
        "Windows Server",
        "Linux",
        "VMware",
        "Active Directory",
        "PowerShell",
        "Bash",
        "Azure",
        "ITIL",
      ],
      educationRequirements: "B.E./B.Tech in Computer Science or related field",
      experienceLevel: "3-5 years",
      salaryRange: "₹8 LPA - ₹12 LPA",
      companyLogo: "https://via.placeholder.com/150?text=InfraCore+Logo",
    },
    {
      id: "123",
      jobTitle: "Content Strategist",
      companyName: "StoryVibe",
      location: "Mumbai",
      industryType: "Content Marketing",
      department: "Marketing",
      employmentType: "Full-time",
      roleCategory: "Content Strategy",
      shortDescription:
        "Develop content strategies to engage audiences. Create and manage editorial calendars. Work in Mumbai’s creative hub. Join a storytelling team.",
      jobDescription:
        "StoryVibe is seeking a Content Strategist to join our Mumbai team, focusing on crafting compelling content strategies. You will develop and execute content plans to drive brand engagement across blogs, social media, and newsletters. Your role involves researching audience needs, creating editorial calendars, and collaborating with writers and designers to produce high-quality content. You will analyze content performance using tools like Google Analytics and adjust strategies for maximum impact. The ideal candidate has experience with SEO, content management systems like WordPress, and storytelling frameworks. You will also manage content budgets and coordinate with external agencies. StoryVibe offers a creative environment with opportunities to work on diverse campaigns. Knowledge of video content strategy is a plus. This role provides growth in content marketing expertise. Join StoryVibe to tell stories that resonate!",
      jobHighlights: [
        "Creative Environment",
        "Diverse Campaigns",
        "Health Benefits",
      ],
      keySkills: [
        "SEO",
        "Google Analytics",
        "WordPress",
        "Storytelling",
        "Editorial Calendars",
        "Content Budgeting",
        "Social Media",
        "Video Content",
      ],
      educationRequirements:
        "Bachelor’s in Marketing, Journalism, or related field",
      experienceLevel: "2-4 years",
      salaryRange: "₹8 LPA - ₹12 LPA",
      companyLogo: "https://via.placeholder.com/150?text=StoryVibe+Logo",
    },
    {
      id: "124",
      jobTitle: "ERP Consultant",
      companyName: "GrowERP",
      location: "Bangalore",
      industryType: "Consulting",
      department: "ERP Implementation",
      employmentType: "Full-time",
      roleCategory: "ERP Consulting",
      shortDescription:
        "Implement and customize ERP solutions for clients. Gather requirements and provide training. Work in Bangalore’s tech hub. Join a transformative ERP team.",
      jobDescription:
        "GrowERP is hiring an ERP Consultant to join our Bangalore team, focusing on delivering tailored ERP solutions. You will implement and customize platforms like SAP, Oracle NetSuite, or Odoo, ensuring alignment with client business processes. Your role involves gathering requirements, designing workflows, and providing end-user training. You will collaborate with technical teams to integrate ERP systems with existing infrastructure and troubleshoot issues. The ideal candidate has experience with ERP modules like finance, HR, or supply chain, and strong problem-solving skills. You will also document processes and provide post-implementation support. GrowERP offers a transformative environment with opportunities to work on global projects. Certifications like SAP Certified Associate are a plus. This role provides growth in ERP expertise. Join GrowERP to streamline business operations!",
      jobHighlights: [
        "Global Projects",
        "Transformative Environment",
        "Health Benefits",
      ],
      keySkills: [
        "SAP",
        "Oracle NetSuite",
        "Odoo",
        "Workflow Design",
        "Training",
        "Integration",
        "Problem Solving",
        "Documentation",
      ],
      educationRequirements: "B.E./B.Tech or MBA",
      experienceLevel: "3-5 years",
      salaryRange: "₹12 LPA - ₹18 LPA",
      companyLogo: "https://via.placeholder.com/150?text=GrowERP+Logo",
    },
    {
      id: "125",
      jobTitle: "Robotics Engineer",
      companyName: "RoboTech",
      location: "Chennai",
      industryType: "Robotics",
      department: "Engineering",
      employmentType: "Full-time",
      roleCategory: "Robotics Engineering",
      shortDescription:
        "Design and program robotic systems for automation. Integrate sensors and AI algorithms. Work in Chennai’s tech hub. Join an innovative robotics team.",
      jobDescription:
        "RoboTech is hiring a Robotics Engineer to join our Chennai team, focusing on developing cutting-edge robotic systems. You will design and program robots using ROS and Python, integrating sensors like LiDAR and cameras for autonomous navigation. Your role involves developing control algorithms, optimizing path planning, and testing systems in real-world scenarios. You will collaborate with mechanical engineers to ensure hardware-software integration and with AI teams to implement machine learning models. The ideal candidate has experience with SLAM, computer vision, and embedded systems. You will also contribute to simulation testing using Gazebo and document technical specifications. RoboTech offers an innovative environment with access to advanced robotics labs. Knowledge of industrial automation protocols is a plus. This role provides growth in robotics expertise. Join RoboTech to automate the future!",
      jobHighlights: [
        "Advanced Labs",
        "Innovative Environment",
        "Health Benefits",
      ],
      keySkills: [
        "ROS",
        "Python",
        "SLAM",
        "Computer Vision",
        "LiDAR",
        "Path Planning",
        "Gazebo",
        "Embedded Systems",
      ],
      educationRequirements: "B.E./B.Tech in Robotics or Computer Science",
      experienceLevel: "3-5 years",
      salaryRange: "₹12 LPA - ₹18 LPA",
      companyLogo: "https://via.placeholder.com/150?text=RoboTech+Logo",
    },
    {
      id: "126",
      jobTitle: "Salesforce Developer",
      companyName: "CloudCRM",
      location: "Pune",
      industryType: "CRM",
      department: "Engineering",
      employmentType: "Full-time",
      roleCategory: "Salesforce Development",
      shortDescription:
        "Develop and customize Salesforce solutions. Integrate CRM with external systems. Work in Pune’s tech hub. Join a dynamic CRM team.",
      jobDescription:
        "CloudCRM is hiring a Salesforce Developer to join our Pune team, focusing on building tailored CRM solutions. You will develop and customize Salesforce applications using Apex, Visualforce, and Lightning Components to meet client needs. Your role involves integrating Salesforce with external systems via APIs and designing workflows to automate business processes. You will collaborate with business analysts to gather requirements and provide technical support to users. The ideal candidate has experience with Salesforce Administration, SOQL, and DevOps tools like Gearset. You will also contribute to unit testing and documentation for compliance. CloudCRM offers a dynamic environment with opportunities to earn Salesforce certifications. Knowledge of Salesforce Marketing Cloud is a plus. This role provides growth in CRM expertise. Join CloudCRM to enhance customer relationships!",
      jobHighlights: [
        "Certification Support",
        "Dynamic Environment",
        "Health Benefits",
      ],
      keySkills: [
        "Apex",
        "Visualforce",
        "Lightning Components",
        "SOQL",
        "Gearset",
        "API Integration",
        "Workflow Automation",
        "Unit Testing",
      ],
      educationRequirements: "B.E./B.Tech in Computer Science or related field",
      experienceLevel: "3-5 years",
      salaryRange: "₹12 LPA - ₹18 LPA",
      companyLogo: "https://via.placeholder.com/150?text=CloudCRM+Logo",
    },
    {
      id: "127",
      jobTitle: "Data Engineer",
      companyName: "StreamData",
      location: "Bangalore",
      industryType: "Big Data",
      department: "Data Engineering",
      employmentType: "Full-time",
      roleCategory: "Data Engineering",
      shortDescription:
        "Build and maintain data pipelines for analytics. Optimize data workflows in cloud environments. Work in Bangalore’s tech hub. Join a data-driven team.",
      jobDescription:
        "StreamData is hiring a Data Engineer to join our Bangalore team, focusing on building robust data pipelines. You will design and implement ETL processes using tools like Apache Spark, Airflow, and Snowflake to support analytics and machine learning. Your role involves optimizing data workflows, ensuring data quality, and integrating with cloud platforms like AWS or GCP. You will collaborate with data scientists and analysts to deliver clean, accessible datasets. The ideal candidate has experience with big data technologies, SQL, and Python scripting. You will also contribute to data governance and security practices. StreamData offers a data-driven environment with opportunities to work on large-scale projects. Knowledge of real-time streaming with Kafka is a plus. This role provides growth in data engineering expertise. Join StreamData to power data-driven decisions!",
      jobHighlights: [
        "Large-scale Projects",
        "Data-driven Culture",
        "Health Benefits",
      ],
      keySkills: [
        "Apache Spark",
        "Airflow",
        "Snowflake",
        "SQL",
        "Python",
        "AWS",
        "GCP",
        "Kafka",
      ],
      educationRequirements: "B.E./B.Tech in Computer Science or related field",
      experienceLevel: "3-5 years",
      salaryRange: "₹12 LPA - ₹18 LPA",
      companyLogo: "https://via.placeholder.com/150?text=StreamData+Logo",
    },
    {
      id: "128",
      jobTitle: "IT Project Manager",
      companyName: "TechFlow",
      location: "Mumbai",
      industryType: "IT Services",
      department: "Project Management",
      employmentType: "Full-time",
      roleCategory: "Project Management",
      shortDescription:
        "Lead IT projects from planning to delivery. Manage budgets and stakeholder expectations. Work in Mumbai’s tech hub. Join a results-driven PM team.",
      jobDescription:
        "TechFlow is hiring an IT Project Manager to join our Mumbai team, focusing on delivering successful IT projects. You will plan, execute, and monitor projects, ensuring they meet scope, budget, and timeline requirements. Your role involves coordinating with cross-functional teams, managing risks, and communicating progress to stakeholders. You will use tools like MS Project and Jira to track tasks and resources. The ideal candidate has experience with agile and waterfall methodologies, along with strong leadership skills. You will also manage vendor relationships and ensure quality deliverables. TechFlow offers a results-driven environment with opportunities to lead high-impact projects. PMP or Prince2 certification is a plus. This role provides growth in project management expertise. Join TechFlow to drive IT success!",
      jobHighlights: [
        "High-impact Projects",
        "Results-driven Culture",
        "Health Benefits",
      ],
      keySkills: [
        "MS Project",
        "Jira",
        "Agile",
        "Waterfall",
        "Risk Management",
        "Stakeholder Communication",
        "Vendor Management",
        "Leadership",
      ],
      educationRequirements: "B.E./B.Tech or MBA",
      experienceLevel: "5-8 years",
      salaryRange: "₹15 LPA - ₹22 LPA",
      companyLogo: "https://via.placeholder.com/150?text=TechFlow+Logo",
    },
    {
      id: "129",
      jobTitle: "Graphic Designer",
      companyName: "PixelCraft",
      location: "Delhi",
      industryType: "Design Services",
      department: "Creative",
      employmentType: "Full-time",
      roleCategory: "Graphic Design",
      shortDescription:
        "Create stunning visuals for digital and print media. Collaborate with marketing teams for brand consistency. Work in Delhi’s creative hub. Join a vibrant design team.",
      jobDescription:
        "PixelCraft is hiring a Graphic Designer to join our Delhi team, focusing on creating impactful visuals. You will design graphics for websites, social media, and print materials using tools like Adobe Photoshop, Illustrator, and InDesign. Your role involves collaborating with marketing teams to ensure brand consistency and developing creative concepts for campaigns. You will also create motion graphics and UI elements for digital platforms. The ideal candidate has a strong portfolio, experience with typography, and knowledge of design trends. You will participate in brainstorming sessions and present ideas to clients. PixelCraft offers a vibrant environment with opportunities to work on diverse projects. Knowledge of 3D design tools like Blender is a plus. This role provides growth in creative design expertise. Join PixelCraft to bring ideas to life!",
      jobHighlights: [
        "Vibrant Environment",
        "Diverse Projects",
        "Health Benefits",
      ],
      keySkills: [
        "Photoshop",
        "Illustrator",
        "InDesign",
        "Typography",
        "Motion Graphics",
        "UI Design",
        "Branding",
        "3D Design",
      ],
      educationRequirements: "Bachelor’s in Graphic Design or related field",
      experienceLevel: "2-4 years",
      salaryRange: "₹8 LPA - ₹12 LPA",
      companyLogo: "https://via.placeholder.com/150?text=PixelCraft+Logo",
    },
  ];

  return NextResponse.json(jobs);
}
